apiVersion: v1
kind: Secret
metadata:
  name: payment-eapi-secrets
  namespace: payment-system
  labels:
    app: payment-eapi
    component: api
    tier: external
    part-of: payment-system
type: Opaque
data:
  # Note: The following values should be properly base64 encoded in a real deployment
  # They are shown as placeholders here for illustration purposes
  
  # Redis credentials
  REDIS_PASSWORD: base64_encoded_redis_password
  
  # Conjur vault integration credentials
  CONJUR_URL: base64_encoded_conjur_url
  CONJUR_ACCOUNT: base64_encoded_conjur_account
  CONJUR_AUTHN_LOGIN: base64_encoded_conjur_authn_login
  CONJUR_AUTHN_API_KEY: base64_encoded_conjur_authn_api_key
  CONJUR_SSL_CERTIFICATE: base64_encoded_conjur_ssl_certificate
  
  # JWT token configuration for secure service-to-service communication
  JWT_SIGNING_KEY: base64_encoded_jwt_signing_key
  
  # Internal service URL (sensitive because it's an internal endpoint)
  PAYMENT_SAPI_URL: base64_encoded_payment_sapi_url
  
  # Application configuration
  SPRING_PROFILES_ACTIVE: base64_encoded_spring_profiles_active