apiVersion: v1
kind: Secret
metadata:
  name: payment-sapi-secrets
  namespace: payment-system
  labels:
    app: payment-sapi
    component: api
    tier: internal
    part-of: payment-system
  annotations:
    kubernetes.io/description: "Contains sensitive configuration for the Payment-SAPI component"
type: Opaque
data:
  # Database password for connecting to the PostgreSQL database
  DB_PASSWORD: cGFzc3dvcmQxMjM=  # password123
  
  # Password for authenticating with the Redis cache server
  REDIS_PASSWORD: cmVkaXNwYXNzd29yZDEyMw==  # redispassword123
  
  # Public key used to verify JWT token signatures issued by Payment-EAPI
  TOKEN_VERIFICATION_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzOWpZNDVLcXB6R2x3NkFjUWZVbQpFVC9HNmJZSEE0VnJiWXVpWmMrTjRjL1pJMEFhRUF5ZGU2UXdTQlZHVnpPZXZmODJUd0VnZTNZcmJZSTVDWnhyCkRBQ0ZLRGpHL3dNR1FkSjZvK2FMZHZwVmErQ0VxcGNqUDZCYXptQlFtUm9JTjcvQTRiZStrWlBYNGw1QU1XMisKWU9HQkxVMVZPUUxsWVNEQVpCSzVDWkFpNGt5TXUyYjRyTWFpWUVrVENHK1VvL0pQeFVSY3ZFbDYzSlFRMEtLVwpXWWR1YmhjVTFnK1hiMWJhRDJWZHVUWVpOQmhxZVJWNU5kcGFMbHo2TmFXVGIvQ2VXbjJPcHlGQ2JxUUVZZz09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
  
  # Shared secret used for secure token renewal requests to Payment-EAPI
  PAYMENT_EAPI_TOKEN_RENEWAL_SECRET: dG9rZW5yZW5ld2Fsc2VjcmV0MTIz  # tokenrenewal123
  
  # Active Spring profile, set to 'prod' for production environment
  SPRING_PROFILES_ACTIVE: cHJvZA==  # prod