spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/rotation_dev
    username: rotation_dev
    password: rotation_dev_password
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
    password: ''
    ssl: false
    timeout: 2000
    database: 0

conjur:
  url: http://localhost:8080/conjur
  account: payment-system-dev
  authn-login: rotation-service-dev
  ssl-certificate: src/test/resources/conjur-dev.pem

rotation:
  default-transition-period-minutes: 5
  auto-rotation-enabled: true
  notification-endpoint: http://localhost:8080/api/notifications

logging:
  level:
    com.payment.rotation: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'