global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'payment-api-monitor'

rule_files:
  - /etc/prometheus/alert-rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
      scheme: 'http'
      timeout: '5s'
      api_version: 'v2'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  - job_name: 'payment-eapi'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-eapi:8080']
        labels:
          service: 'payment-eapi'

  - job_name: 'payment-sapi'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-sapi:8081']
        labels:
          service: 'payment-sapi'

  - job_name: 'redis-cache'
    scrape_interval: 15s
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis-cache'

  - job_name: 'conjur-vault'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['conjur:9090']
        labels:
          service: 'conjur-vault'

  - job_name: 'postgresql'
    scrape_interval: 30s
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgresql'

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-metrics'

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'container-metrics'

  - job_name: 'credential-rotation'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['credential-rotation:8083']
        labels:
          service: 'credential-rotation'

  - job_name: 'monitoring-api'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['monitoring:8084']
        labels:
          service: 'monitoring-api'

storage:
  tsdb:
    path: '/prometheus'
    retention_time: '30d'
    retention_size: '0'