# Application configuration for Payment-SAPI service
# Part of the Payment API Security Enhancement project

spring:
  application:
    name: payment-sapi
  
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: payment_user
    password: payment_password
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
  
  # Redis cache configuration for token storage
  redis:
    host: localhost
    port: 6379
    password: ''
    ssl: false
    timeout: 2000
    database: 0
    lettuce:
      pool:
        min-idle: 2
        max-idle: 10
        max-active: 20
        time-between-eviction-runs: 300000
  
  # Cache configuration
  cache:
    type: redis
    redis:
      time-to-live: 3600000  # 1 hour in milliseconds
    cache-names: tokens
  
  # Database migration configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true
  
  # Active profile configuration
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# Server configuration
server:
  port: 8081
  servlet:
    context-path: /internal/v1
  tomcat:
    threads:
      max: 100
    max-connections: 5000

# Token validation configuration
token:
  audience: payment-sapi
  issuers: payment-eapi
  verification-key-path: conjur/path/to/verification-key
  renewal-enabled: true
  renewal-threshold-seconds: 300

# Payment backend integration
payment:
  backend:
    url: http://payment-backend:8083
    connection-timeout: 5000
    read-timeout: 10000
    retry-count: 2

# Monitoring and management
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Logging configuration
logging:
  level:
    root: INFO
    com.payment.sapi: INFO
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Circuit breaker configuration
circuit-breaker:
  redis:
    failure-threshold: 50
    wait-duration-in-open-state: 15000
    permitted-number-of-calls-in-half-open-state: 20
  payment-backend:
    failure-threshold: 50
    wait-duration-in-open-state: 15000
    permitted-number-of-calls-in-half-open-state: 20

# Security configuration
security:
  rate-limiting:
    enabled: true
    limit-per-minute: 1000
    burst-capacity: 2000
  headers:
    content-security-policy: "default-src 'self'"
    x-content-type-options: nosniff
    x-frame-options: DENY
    x-xss-protection: 1; mode=block
    strict-transport-security: max-age=31536000; includeSubDomains