spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_dev
    username: payment_dev
    password: payment_dev_password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    host: localhost
    port: 6379
    password: ''
    ssl: false
    database: 0
    lettuce:
      pool:
        min-idle: 2
        max-idle: 10
        max-active: 20
        time-between-eviction-runs: 300000
  flyway:
    enabled: true
    clean-on-validation-error: false
    clean-disabled: true

server:
  port: 8081
  tomcat:
    threads:
      max: 50
    max-connections: 1000

token:
  audience: payment-sapi-dev
  issuers: payment-eapi-dev
  verification-key-path: conjur/path/to/dev-verification-key
  renewal-enabled: true
  renewal-threshold-seconds: 300

payment:
  backend:
    url: http://localhost:8083
    connection-timeout: 5000
    read-timeout: 10000
    retry-count: 2

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    com.payment.sapi: DEBUG
    org.springframework: INFO
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

circuit-breaker:
  redis:
    failure-threshold: 50
    wait-duration-in-open-state: 15000
    permitted-number-of-calls-in-half-open-state: 20
  payment-backend:
    failure-threshold: 50
    wait-duration-in-open-state: 15000
    permitted-number-of-calls-in-half-open-state: 20

security:
  rate-limiting:
    enabled: true
    limit-per-minute: 300
    burst-capacity: 500
  headers:
    content-security-policy: "default-src 'self'"
    x-content-type-options: nosniff
    x-frame-options: DENY
    x-xss-protection: 1; mode=block
    strict-transport-security: max-age=31536000; includeSubDomains